### ISSUE TITLE
Compiling in VS2010

### ISSUE THREAD

**Issue by johnnyontheweb** [SlimDX/slimdx#508]
I'm trying to compile SlimDX under VS2010, but I cannot use Debub because I don't find a way to define the macro DXSDK_DIR. I tried also creating a system variable, but nothing. How can I change it for all projects?

Secondly, I cannot compile with "Public" because the linker says:
`error LNK1256: ALINK operation failed (80040414): 'D:\slimdxKey.snk' not found`
can you help?

**Comment by Promit** [comment]
DXSDK_DIR should be set when you install the June 2010 DX SDK - you may need to log out or reboot after installation for it to take effect. If you can't do that for whatever reason, you'll need to go into project properties and manually set the include directory explicitly. 

Public builds are signed, and aren't intended to be possible for anyone except us. If you want to copy our release process, you can create your own digital signature and feed it in.
https://msdn.microsoft.com/en-us/library/dd788548.aspx

**Comment by johnnyontheweb** [comment]
Thanks, very clear. There's no need for me to sign the DLLs.

For the first question: will I be able to use the Release binaries instead of the ones from Public with no difference? If I redistribute them, will I need your the signed files from you?
The main reason for such questions is that I suspect that the ones in the slimdx website are old and do not includes the latter commits listed here. Am I wrong? I just want to make sure to use the latest files.

**Comment by Promit** [comment]
It is only necessary to sign the binaries if you wish to install them into the GAC rather than using them privately. I don't generally recommend doing this unless you have special deployment requirements, and it will conflict with our releases on the same machine unless you make changes to version or assembly id. A privately used Release build should be just fine for most people. We don't do anything special for Public apart from configuring it to be a globally installed library.

**Comment by johnnyontheweb** [comment]
So, the provided installers for the SlimDX runtimes are out-of date. I'll try to use the DLLs recompiled from here.
Many thanks for the infos, regards
